checking for container libs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -42,23 +42,29 @@ jobs:
       #    restore-keys: |
       #      ${{ runner.os }}-build-${{ env.cache-name }}-
       
+      # Building the docker image and validating it was made.
       - name: Build backend
-        run: docker compose build backend --no-cache
-
-      - name: Validate backend image
-        run: docker images | grep backend || (echo "Error = Backend image not found" && exit 1)
+        run: | 
+          docker compose build backend --no-cache
+          docker images | grep backend || (echo "Error = Backend image not found" && exit 1)
       
       # TODO: Run pytests here using docker compose run or something
       
       # Note that any error will immediatly trigger the contianer to be shut down.
+      # Start backend and check it health.
       - name: Start backend
         run: |
+            apt-get update && apt-get install -y net-tools coreutils
+
             docker compose up --no-build --detach backend
 
             docker ps  # Check if container is running
-            #docker compose logs backend  # Check backend logs 
+            docker compose logs backend  # Check backend logs 
 
-            docker exec rubricapp-backend-1 pip freeze
+            (pip freeze | sed 's/[>=]//g' | awk -F '==' '{print $1, $2}' | sort) > installed.txt
+            (sed 's/[>=]//g' BackEndFlask/requirements.txt | awk -F '==' '{print $1, $2}' | sort) > expected.txt
+            comm -3 installed_sorted.txt expected_sorted.txt | column -t
+            rm -f -v installed.txt expected.txt 
 
             netstat -tulpn | grep 5050  # Check if port is actually listening
             sleep 5
